- win_reboot:

- name: Install Ad
  win_feature: 
    name: AD-Domain-Services
    state: present

- win_reboot:

#- win_domain_membership: i
#    workgroup_name: domain
#    dns_domain_name: ad1.4f52.example.opentlc.com
#    domain_admin_user: admin@ad1.4f52.example.opentlc.com
#    domain_admin_password: jVMijRwLbI02gFCo2xkjlZ9lxEA7bm7zgg==
#    state: domain 
#  register: domain_state

- win_domain:
    dns_domain_name: ad1.747f.example.opentlc.com
    safe_mode_password: jVMijRwLbI02gFCo2xkjlZ9lxEA7bm7zgg==

- win_reboot:

#- shell: nltest /dclist:"{{ ad_domain_name }}"
#- win_shell: echo %HOMEDIR%
#  args:
#    executable: cmd nltest /dclist:"{{ ad_domain_name }}"
