- name: Ensure user are present
  win_domain_user:
    name: "{{item.name}}"
    firstname: "{{item.firstname}}"
    surname: "{{item.surname}}"
    password: "{{item.password}}"
    state: present
  with_items: "{{ user_info }}"
